[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "A1 Sim to real Extension"
author = "Sathvik Kadimisetty"
maintainer = "Sathvik Kadimisetty"
description="Extension containing A1's code for robot learning."
repository = "https://github.com/Jellal-17/A1_Sim-to-real-IsaacLab.git"
keywords = ["navigation", "extension", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "omni.isaac.a1_tasks"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
